= @@MY_PROJECT@@
:toc:
:toclevels: 4
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

A repository for @@MYPROJECT@@.

For information regarding versioning, see link:VERSIONING.adoc[Versioning].

== Python

=== Usage

==== Building and using `@@MYPROJECT@@`

* With `pip`
+
[source,bash]
----
python -m pip install setuptools_scm[toml]
python -m pip install .
----
* With `build` and `pip`
+
[source,bash]
----
python -m pip install build
python -m build
python -m pip install ./dist/*.whl
----

==== Using `@@MYPROJECT@@` in another project


* Install
** From the VCS URL
+
[source,bash]
----
# From the cloned repository
python3 -m pip install .

# From the Git URL
python3 -m pip install git+https://github.com/bar/@@MYPROJECT@@.git

# From the Git URL from a branch
python3 -m pip install git+https://github.com/bar/@@MYPROJECT@@.git@main

# From the Git URL from tag
python3 -m pip install git+https://github.com/bar/@@MYPROJECT@@.git@v0.0.2
----

==== Importing `@@MYPROJECT@@`

Import into another Python script or module with a standard `import` call:
[source,python]
----
import @@MYPROJECT@@
----

Look below for examples using the `@@MYPROJECT@@` in `pyproject.toml`, `setup.py`, and `requirements.txt` based projects.

For more information regarding VCS versioning and dependency managment, see the following references

- https://setuptools.pypa.io/en/latest/userguide/dependency_management.html[Setuptools Dependency Management]
- pip's documentation on https://pip.pypa.io/en/latest/topics/vcs-support/[VCS support]

==== Using the `@@MYPROJECT@@` OS Package

@@MYPROJECT@@ is offered as an OS package (an `rpm`), this package installs @@MYPROJECT@@ and its dependencies into
a virtual environment on the system. The package will depend on a flavor of the `python-base` package
respective to the distribution being used.

. To install and activate the virtualenv:
+
[source,bash]
----
zypper --plus-repo=https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-$(awk -F= '/VERSION=/{gsub(/["-]/, "") ; print tolower($NF)}' /etc/os-release)/ --no-gpg-checks in @@MYPROJECT@@
----
. Then use `@@MYPROJECT@@`.
- Activate the virtual environment
+
[source,bash]
----
source /usr/lib/@@MYPROJECT@@/python/bin/activate
----
- Use the package ad-hoc in a Python interpreter:
+
[source,bash]
----
/usr/lib/@@MYPROJECT@@/python/bin/python
----
+
[source,python]
----
import @@MYPROJECT@@
----

===== Importing `@@MYPROJECT@@` with a `pyproject.toml` or `setup.py` file

For `setup.py` files, the GitHub source can be included in another project by adding a `dependency_links=[]` parameter in the `setup()` function call.

* `pyproject.toml` by branch name, git-tag, or git release
+
[source,toml]
----
[project]
# ...
dependencies = [
    "@@MYPROJECT@@ @ git+https://github.com/bar/@@MYPROJECT@@.git@main",
    "@@MYPROJECT@@ @ git+https://github.com/bar/@@MYPROJECT@@.git@v1.0.2",
    "@@MYPROJECT@@ @ git+https://github.com/bar/@@MYPROJECT@@.git@eleases/tag/v1.0.1",
]
----
* `setup.py` by branch name, git-tag, or git release
+
[source,python]
----
setup(
    # ...
    install_requires=[
        # ...
        "@@MYPROJECT@@ @ git+https://github.com/bar/@@MYPROJECT@@.git@main",
        "@@MYPROJECT@@ @ git+https://github.com/bar/@@MYPROJECT@@.git@v1.0.2",
        "@@MYPROJECT@@ @ git+https://github.com/bar/@@MYPROJECT@@.git@eleases/tag/v1.0.1",
    ],
),
----

===== Importing `@@MYPROJECT@@` with a `requirements.txt` file

Add a line like the ones below to a `requirements.txt` file.

* By branch name
+
[source,python]
----
git+git://github.com/bar/@@MYPROJECT@@.git@master#egg=@@MYPROJECT@@
----
* By git tag
+
[source,python]
----
git+git://github.com/bar/@@MYPROJECT@@.git@v1.0.2#egg=@@MYPROJECT@@
----
* By release
+
[source,python]
----
git+git://github.com/bar/@@MYPROJECT@@.git@releases/tag/v1.0.1#egg=@@MYPROJECT@@
----

=== Contributing

Contributions can be in the form of:

* Python code that can be imported and used in Python scripts
* Callables for the command line that make use of one or more functions/modules

==== Adding new commands

When a new or existing module of `@@MYPROJECT@@` wants to offer a command line function an `entry_point` can be used.

For example, if we wanted a command called `example-do-stuff` to exist on the command line that invoked some code within a `@@MYPROJECT@@` submodule like the
code below:

[source,python]
----
# file: ./@@MYPROJECT@@/example/service.py
def do_stuff() -> None:
    thing = 'cool stuff'
    print(f'Doing {thing}')
    @@MYPROJECT@@(thing)

def @@MYPROJECT@@(stuff: str) -> None:
    with open('/tmp/@@MYPROJECT@@', 'w') as file:
        file.write(f'finished doing {stuff}')
----

Then we could add an Entry Point to the `entry_points.ini` file

[source,ini]
----
[console_scripts]
example-do-stuff = '@@MYPROJECT@@.example.service:do_stuff'
----

