= Versioning

The version is derived from Git by the `setuptools_scm` Python module and follows https://peps.python.org/pep-0440/#abstract[PEP0440]'s version identification
and dependency specification for https://peps.python.org/pep-0440/#final-releases[final] and https://peps.python.org/pep-0440/#pre-releases[pre] releases.

== Classification

The items below denote how stable, pre-release, and unstable versions are classified through
version strings.

* *_(stable) release_*: A git-tag following the `X.Y.Z` semver format is considered a stable, release version.
[source,text]
----
# Format:
# {tag}
# X.Y.Z
# X - Major
# Y - Minor
# Z - Micro (a.k.a. patch)
0.1.2
----

* *_(stable) post-release_*: A git-tag following the `X.Y.Z.postN` (where `N` is an integer), indicates a post-release.
 These are seldom used, and are strictly for handling documentation, packaging, or other meta
 updates after a release tag was already created where it isn't warranted to publish an
 entirely new release.
[source,text]
----
# Format:
# {tag}
# X.Y.Z.postN
# X - Major
# Y - Minor
# Z - Micro (a.k.a. patch)
# Z - Post release [1-9]+
0.1.2.post1
----

NOTE: `X.Y.Z.post0` is equivalent to `X.Y.Z`, `post0` indicates the first release.

* *_(unstable) pre-release_*: A git-tag with an `a`(lpha), `b`(eta), or `r`(elease) `c`(andidate) annotation and an identification number `N` denotes a pre-release/preview.

&gt; These are sometimes created before an official release (e.g. 1.7.0a1 might exist before 1.7.0 is released).
 &gt; Additionally the beta and release candidate tags may be skipped.
 &gt; Whether an alpha, beta, or release candidate pre-release is taken is entirely up to the application's release management team.

----
```text
# Format:
# {tag}[{a|b|rc}N]
0.1.2a1
0.1.2b1
0.1.2rc1
```
----

* *_(unstable) development_*: Development builds *auto-increment* the micro version (the `Z` in `X.Y.Z`) or pre-release version (the `N` in `X.Y.Z{[a|b|rc]N}`), and
 then append a suffix based on whether the working directory was *clean*, *dirty*, or *mixed*.
** *_clean_*: When the version shows an appended `devN+{scm_letter}{revision_short_hash}`, that means there have been commits made since the previous git-tag.

[source,text]
----
# Format:
# {next_version}.dev{distance}+{scm_letter}{revision_short_hash}

# If the previous git-tag was 0.1.2:
           0.1.3.dev4+g818da8a

# If the previous get-tag was a pre-release of 0.1.3a1:
         0.1.3a2.dev4+g818da8a
----

** *_dirty_* When the version shows an appended `.d{YYYYMMDD}` datestamp, that means there were modified/uncommitted changes in the working directory when the application was built.

[source,text]
----
# Format:
# {next_version}.d(datestamp}

# If the previous git-tag was 0.1.2:
           0.1.3.d20230123

# If the previous get-tag was a pre-release of 0.1.3a1:
         0.1.2a2.d20230123
----

** *_mixed_* When the version shows a development tag with an appended datestamp, this means commits have been made but there were uncommitted changes present in the working directory when the application was built.

[source,text]
----
# Format:
# {next_Version}.dev{distance}+{scm_letter}{revision_short_hash}.d{datestamp}

# If the previous git-tag was 0.1.2:
           0.1.3.dev3+g3071655.d20230123

# If the previous get-tag was a pre-release of 0.1.3a1:
         0.1.3a2.dev3+g3071655.d20230123
----

== Configuration

The `setuptools_scm` module is configured by `pyproject.toml`.

For more information regarding configuration of `setuptools_scm`, see https://github.com/pypa/setuptools_scm/#version-number-construction[version number construction].
